INPUT_PATH = '/Users/cthorpe/science/code/pipelines/structure_pipeline/input'
OUTPUT_PATH = '/Users/cthorpe/science/code/pipelines/structure_pipeline/output'
ASSET_PATH = '/Users/cthorpe/science/code/pipelines/structure_pipeline/assets'



